### ISSUE TITLE
FI Altered Sequence Error

### ISSUE THREAD

**Issue by wdrav** [SynBioDex/Excel-utilities#5]
When "Codon optimization" is specified in the "Altered Sequence" column,  the current version of Excel-to-SBOL implements the "https://wiki.synbiohub.org/wiki/Terms/synbiohub#alteredSequence", while the SBOL-Utilities version does not implement this tag.

**Comment by jakebeal** [comment]
The SBOL-utilities version doesn't implement this property because we don't currently have any reason to use it. Having the property in the files, however, would not be a problem, as it will just be ignored.

My recommendation would be to configure the column to be optional, i.e., if there is nothing in the cell, do not put an #alteredSequence property on the Component. If there is a value in the cell, then set the property. 

I would argue that this is the desirable behavior, because people may put in altered sequences but not mark them. If there is no data, Excel-to-SBOL thus cannot know whether the property should be true or false.

**Comment by cjmyers** [comment]
I agree with Jake.  We should not serialize unused columns.  We could also delete the column and its configuration, if we think it is not needed for the iGEM use case.

**Comment by wdrav** [comment]
Sounds good. @jakebeal, Excel-to-SBOL does ignore this column if there is no value put in to the cell. Will leave as is.
